server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://kimth-lab.c2dfz3ys9r7s.ap-northeast-2.rds.amazonaws.com:30000/smart_building_supervision_platform?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: seoulman2000!
  mail:
    host: smtp.naver.com
    port: 465
    username: cwctboy@naver.com
    password: seoulman2000!
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            trust: smtp.naver.com
            enable: true
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher