server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: ENC(JZw+Rob7dBHsn5xEcfI4ztW+v0u5LRn4iYSm99bhww2UDu8nfbz9WQXCidyJuWY2s46N2GfdU8E/dZucZyeVE2Ajtheshw0uxZzDDjCTId+l1gWsO8N8b7Xmcv4h2MTF)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(r2dQ7kwNsuiVR/OM6rMZ3Q==)
    password: ENC(EhMDMWjKSOgdWlEhfizTknA+Np4h0Ni8)

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor